export enum TagType {
  DATE = 'date',
  YEAR = 'year',
  MONTH = 'month',
  DAY = 'day',
  USER = 'user',
  FILE = 'file',
  FOLDER = 'folder',
  TYPE = 'type',
  CATEGORY = 'category',
  TAG = 'tag',
  LABEL = 'label',
  EMOTION = 'emotion',
  DEFAULT = 'default',
}
